### data generated by: `DaphniaPulex20162017Sequencing/AlanAnalysis/QTL_overlap_analysis/collect_overlap_tests.R`

### libraries
  library(data.table)
  library(ggplot2)
  library(cowplot)

### load data
  load("/Users/alanbergland/Documents/GitHub/DaphniaPulex20162017Sequencing/AlanFigures/SFigure9_OverlapTest/overlap_perm.Rdata")

overlap.perm <- overlap.perm[cross=="AxC"]
### plot

  p1 <- ggplot() +
  geom_histogram(data=overlap.perm[perm!=0], aes(z)) +
  geom_vline(data=overlap.perm[perm==0], aes(xintercept=z), color="red") +
  facet_grid(~pheno) +
  theme_bw() +
  theme(strip.text = element_text(size = 14),
        axis.text=element_text(size=12),
        axis.title=element_text(size=14))

  ggsave(p1, file="/Users/alanbergland/Documents/GitHub/DaphniaPulex20162017Sequencing/AlanFigures/SFigure9_OverlapTest/overlap.pdf", height=3, w=6)
    ggsave(p1, file="/Users/alanbergland/Documents/GitHub/DaphniaPulex20162017Sequencing/AlanFigures/SFigure9_OverlapTest/overlap.png", height=3, w=6)
