
  ### uses summary file generated by this script: `DaphniaPulex20162017Sequencing/AlanAnalysis/pooledMF/pooledMF_r_hybrids_questionmark.v2.R`

  # scp aob2x@rivanna.hpc.virginia.edu:/nv/vol186/bergland-lab/alan/mf_expectation.Rdata ~/.

  library(ggplot2)
  library(data.table)
  library(cowplot)

  load("/Users/alanbergland/Documents/GitHub/DaphniaPulex20162017Sequencing/AlanFigures/SFigure8_F1Confirmation/mf_expectation.Rdata")

  F1.plot <- ggplot(data=m.ag, aes(x=pool, y=mu)) +
  geom_hline(aes(yintercept=exp.fq/2), linetype="solid", color="red", size=.75) +
  geom_errorbar(aes(ymin=mu-sd, ymax=mu+sd), width=.2, size=.75) +
  geom_point(size=4, fill="white", shape=21, stroke=1) +
  facet_grid(~A.geno+B.geno) +
  ylab("Reference Allele Frequency") +
  xlab("Pool") +
  scale_x_discrete(labels=c("m" = "Male", "f" = "Female")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


  F1.plot

  ggsave("/Users/alanbergland/Documents/GitHub/DaphniaPulex20162017Sequencing/AlanFigures/SFigure8_F1Confirmation/SupplementalFigure_8.pdf")
